/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "surface-muted": "rgb(var(--color-surface-muted) / <alpha-value>)",
        foreground: "rgb(var(--color-foreground) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        subtle: "rgb(var(--color-subtle) / <alpha-value>)",
        card: "rgb(var(--color-background) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-foreground": "rgb(var(--color-primary-foreground) / <alpha-value>)",
        "primary-soft": "rgb(var(--color-primary-soft) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        "success-soft": "rgb(var(--color-success-soft) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        "danger-foreground": "rgb(var(--color-danger-foreground) / <alpha-value>)",
        "danger-soft": "rgb(var(--color-danger-soft) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        "warning-soft": "rgb(var(--color-warning-soft) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        white: "rgb(var(--color-white) / <alpha-value>)",
        black: "rgb(var(--color-black) / <alpha-value>)",
        gray: {
          50: "rgb(var(--color-surface-muted) / <alpha-value>)",
          100: "rgb(var(--color-border) / <alpha-value>)",
          300: "rgb(var(--color-border) / <alpha-value>)",
          400: "rgb(var(--color-subtle) / <alpha-value>)",
          500: "rgb(var(--color-muted) / <alpha-value>)",
          600: "rgb(var(--color-muted) / <alpha-value>)",
          700: "rgb(var(--color-foreground) / <alpha-value>)",
        },
        slate: {
          50: "rgb(var(--color-background) / <alpha-value>)",
          100: "rgb(var(--color-border) / <alpha-value>)",
          200: "rgb(var(--color-border) / <alpha-value>)",
          400: "rgb(var(--color-subtle) / <alpha-value>)",
          500: "rgb(var(--color-muted) / <alpha-value>)",
          600: "rgb(var(--color-muted) / <alpha-value>)",
          700: "rgb(var(--color-foreground) / <alpha-value>)",
          800: "rgb(var(--color-surface-muted) / <alpha-value>)",
        },
        indigo: {
          50: "rgb(var(--color-primary-soft) / <alpha-value>)",
          100: "rgb(var(--color-primary-soft) / <alpha-value>)",
          400: "rgb(var(--color-primary) / <alpha-value>)",
          600: "rgb(var(--color-primary) / <alpha-value>)",
          700: "rgb(var(--color-primary) / <alpha-value>)",
          800: "rgb(var(--color-foreground) / <alpha-value>)",
        },
        red: {
          100: "rgb(var(--color-danger-soft) / <alpha-value>)",
          200: "rgb(var(--color-danger-soft) / <alpha-value>)",
          300: "rgb(var(--color-danger) / <alpha-value>)",
          400: "rgb(var(--color-danger) / <alpha-value>)",
          500: "rgb(var(--color-danger) / <alpha-value>)",
          600: "rgb(var(--color-danger) / <alpha-value>)",
          700: "rgb(var(--color-danger) / <alpha-value>)",
          800: "rgb(var(--color-danger) / <alpha-value>)",
        },
        blue: {
          50: "rgb(var(--color-primary-soft) / <alpha-value>)",
          100: "rgb(var(--color-primary-soft) / <alpha-value>)",
          400: "rgb(var(--color-primary) / <alpha-value>)",
          500: "rgb(var(--color-primary) / <alpha-value>)",
          600: "rgb(var(--color-primary) / <alpha-value>)",
          700: "rgb(var(--color-primary) / <alpha-value>)",
        },
        green: {
          50: "rgb(var(--color-success-soft) / <alpha-value>)",
          100: "rgb(var(--color-success-soft) / <alpha-value>)",
          400: "rgb(var(--color-success) / <alpha-value>)",
          500: "rgb(var(--color-success) / <alpha-value>)",
          600: "rgb(var(--color-success) / <alpha-value>)",
          700: "rgb(var(--color-success) / <alpha-value>)",
        },
        emerald: {
          50: "rgb(var(--color-success-soft) / <alpha-value>)",
          100: "rgb(var(--color-success-soft) / <alpha-value>)",
          500: "rgb(var(--color-success) / <alpha-value>)",
          600: "rgb(var(--color-success) / <alpha-value>)",
          700: "rgb(var(--color-success) / <alpha-value>)",
        },
        amber: {
          50: "rgb(var(--color-warning-soft) / <alpha-value>)",
          100: "rgb(var(--color-warning-soft) / <alpha-value>)",
          500: "rgb(var(--color-warning) / <alpha-value>)",
          600: "rgb(var(--color-warning) / <alpha-value>)",
          700: "rgb(var(--color-warning) / <alpha-value>)",
        },
        yellow: {
          100: "rgb(var(--color-warning-soft) / <alpha-value>)",
          500: "rgb(var(--color-warning) / <alpha-value>)",
          600: "rgb(var(--color-warning) / <alpha-value>)",
          700: "rgb(var(--color-warning) / <alpha-value>)",
        },
        purple: {
          50: "rgb(var(--color-primary-soft) / <alpha-value>)",
          100: "rgb(var(--color-primary-soft) / <alpha-value>)",
          400: "rgb(var(--color-primary) / <alpha-value>)",
          500: "rgb(var(--color-primary) / <alpha-value>)",
          600: "rgb(var(--color-primary) / <alpha-value>)",
          700: "rgb(var(--color-primary) / <alpha-value>)",
        },
        violet: {
          50: "rgb(var(--color-primary-soft) / <alpha-value>)",
          100: "rgb(var(--color-primary-soft) / <alpha-value>)",
          400: "rgb(var(--color-primary) / <alpha-value>)",
          500: "rgb(var(--color-primary) / <alpha-value>)",
          600: "rgb(var(--color-primary) / <alpha-value>)",
          700: "rgb(var(--color-primary) / <alpha-value>)",
        },
        pink: {
          50: "rgb(var(--color-danger-soft) / <alpha-value>)",
          100: "rgb(var(--color-danger-soft) / <alpha-value>)",
          400: "rgb(var(--color-danger) / <alpha-value>)",
          500: "rgb(var(--color-danger) / <alpha-value>)",
          600: "rgb(var(--color-danger) / <alpha-value>)",
        },
        rose: {
          50: "rgb(var(--color-danger-soft) / <alpha-value>)",
          100: "rgb(var(--color-danger-soft) / <alpha-value>)",
          400: "rgb(var(--color-danger) / <alpha-value>)",
          500: "rgb(var(--color-danger) / <alpha-value>)",
          600: "rgb(var(--color-danger) / <alpha-value>)",
        },
      },
    },
  },
  plugins: [],
};
